- fleurs-du-mal/FDM-000-000-000-085.xml
- fleurs-du-mal/FDM-000-000-009-096.xml
- fleurs-du-mal/FDM-000-000-014-061.xml
Sorry Ramona, I did not sync correctly before the last pull request. here's another. this one is better.
> Three new poems

- fleurs-du-mal/FDM-000-000-000-133.xml
Encoding of "Épigraphe pour un livre condamné."
> Épigraphe pour un livre condamné

- fleurs-du-mal/FDM-000-000-011-000.xml
Encoding of "Les Promesses d'un visage."
> Les Promesses d'un visage

- fleurs-du-mal/FDM-000-038-000-039.xml
- fleurs-du-mal/FDM-034-036-000-037.xml
> Critical Apparatus - Two poems

- fleurs-du-mal/FDM-000-000-000-102.xml
Removed E1857 witness from header.
> Corrected File ext & TEI header

- FDM-000-002-000-002.xml
- FDM-025-027-000-028.xml
- FDM-026-028-000-029.xml
- FDM-027-029-000-030.xml
- FDM-042-046-000-047.xml
- fleurs-du-mal/FDM-000-002-000-002.xml
- fleurs-du-mal/FDM-042-046-000-047.xml
Basic markup for three poems - Le Serpent qui danse, Avec ses vetements ondoyants et nacres, L'Albatros.
> 3 Poems - basic markup

- fleurs-du-mal/FDM-000-002-000-002.xml
- fleurs-du-mal/FDM-012-012-000-012.xml
> markup for poem #000-002-000-002

- fleurs-du-mal/FDM-000-124-000-149.xml
- fleurs-du-mal/FDM-000-125-000-150.xml
> Markup for Poem #000-124-000-149

- fleurs-du-mal/FDM-000-000-000-111.xml
> Critical Apparatus - La Lune Offensee

- fleurs-du-mal/FDM-000-000-000-086.xml
- fleurs-du-mal/FDM-000-000-000-089.xml
- fleurs-du-mal/FDM-000-000-000-090.xml
- fleurs-du-mal/FDM-000-000-000-091.xml
- fleurs-du-mal/FDM-000-000-000-095.xml
- fleurs-du-mal/FDM-000-000-000-099.xml
- fleurs-du-mal/FDM-000-000-000-104.xml
- fleurs-du-mal/FDM-000-000-021-000.xml
> Critical Appratus for 000-000-000-086, 091, 099

- fleurs-du-mal/FDM-000-000-008-097.xml
- fleurs-du-mal/FDM-000-000-017-093.xml
- fleurs-du-mal/FDM-006-006-000-006.xml
- fleurs-du-mal/FDM-007-007-000-007.xml
- fleurs-du-mal/FDM-010-010-000-010.xml
- fleurs-du-mal/FDM-030-000-004-000.xml
030-000-004-000, 030-000-004-000, 000-000-008-097
> Three Poems Critical Apparatus

- fleurs-du-mal/FDM-000-000-000-085.xml
- fleurs-du-mal/FDM-042-046-000-047.xml
- fleurs-du-mal/FDM-059-075-000-077.xml
- fleurs-du-mal/FDM-060-076-000-078.xml
- fleurs-du-mal/FDM-061-077-000-079.xml
- fleurs-du-mal/FDM-062-078-000-080.xml
> Basic markup and typos

- fleurs-du-mal/FDM-000-000-014-061.xml
- fleurs-du-mal/FDM-000-000-018-088.xml
- fleurs-du-mal/FDM-000-037-000-038.xml
- fleurs-du-mal/FDM-000-056-000-057.xml
- fleurs-du-mal/FDM-000-057-000-058.xml
- fleurs-du-mal/FDM-000-058-000-059.xml
000-000-018-088
000-056-000-057
000-057-000-058
> 3 Poem Changes

- fleurs-du-mal/FDM-000-059-000-060.xml
- fleurs-du-mal/FDM-000-126-000-151.xml
- fleurs-du-mal/FDM-081-000-003-000.xml
I've corrected the coding of my previous poems so that all XML IDs contain hashtags. 
In Poem "La Voyage,"  (FDM-000-126-000-151) the Lemma contains two quartets combined into an octave, and the witness does not do this. This disrupts the numbering of the stanzas and we have no elegant solution. With Ramona's permission, I'm declaring it a problem.
> FDM-000-126-000-151

- fleurs-du-mal/FDM-077-068-000-070.xml
> FDM-077-068-000-070

- fleurs-du-mal/FDM-021-022-000-023.xml
> RAMONA pos_final_change

- fleurs-du-mal/FDM-016-016-000-017.xml
> Problem poem Orgueil

- fleurs-du-mal/FDM-031-032-000-033.xml
Une nuit que j'etais pres d'une affreuse Juive
> Untitle Poem

- fleurs-du-mal/FDM-000-098-000-122.xml
- fleurs-du-mal/FDM-000-126-000-151.xml
- fleurs-du-mal/FDM-007-007-000-007.xml
- fleurs-du-mal/FDM-076-069-000-071.xml
- fleurs-du-mal/FDM-077-068-000-070.xml
- fleurs-du-mal/FDM-081-000-003-000.xml
Critical apparatus for the two poems, plus one quick typo correction on FDM 077-068-000-070
> FDM 000-098-000-122 and FDM 076-069-000-071

- fleurs-du-mal/FDM-025-027-000-028.xml
- fleurs-du-mal/FDM-082-111-000-136.xml
1. Avec ses vetements ondoyants et nacres
2. Femmes Damnees
> Critical Apparatus Complete

- fleurs-du-mal/FDM-009-009-000-009.xml
- fleurs-du-mal/FDM-013-013-000-013.xml
- fleurs-du-mal/FDM-051-055-000-056.xml
>  	FDM-013-013-000-013, FDM-009-009-000-009, FDM-051-055-000-056

- fleurs-du-mal/FDM-000-038-000-039.xml
> Un Fantome review

- fleurs-du-mal/FDM-030-000-004-000.xml
@Pema-sDaddy Take a look at my review and see if agree with my changes.  😄 
Hugs from Nashville
Ramona
> Review of La Lethe

- fleurs-du-mal/FDM-036-041-000-042.xml
- fleurs-du-mal/FDM-067-095-000-119.xml
- fleurs-du-mal/FDM-074-070-000-072.xml
- fleurs-du-mal/FDM-086-115-000-140.xml
Peer Review of 086-115-000-140
> Peer Review 086-115-000-140

- fleurs-du-mal/FDM-000-000-000-086.xml
> Added a comment to the file

- fleurs-du-mal/FDM-000-000-000-089.xml
- fleurs-du-mal/FDM-000-000-017-093.xml
- fleurs-du-mal/FDM-000-082-000-084.xml
> Review of FDM 000-082-000-084

- fleurs-du-mal/FDM-094-105-000-129.xml
> Les Vin des Chiffonier

- FDM-087-000-007-000.xml
- fleurs-du-mal/FDM-000-038-000-039.xml
Metamorphoses Du Vampire poem review completed.
> FDM-087-000-007-000 Review

- fleurs-du-mal/FDM-010-010-000-010.xml
- fleurs-du-mal/FDM-015-015-000-015.xml
> L'Ennemi done

- fleurs-du-mal/FDM-000-000-023-000.xml
- fleurs-du-mal/FDM-000-002-000-002.xml
> un cabaret folatre
